### PR TITLE
Do not duplicate identifier parts that include parent IDs (fixes #93); expand YV testing

### LINKED ISSUE #93: Make documentary unit URLs shorter when unit ID includes parent's ID
Some CHIs asked whether the URL for documentary units could be shorter and not include duplication when some documentary unit's `<unitid>` is `[parent ID][separator][child ID]`. The URL is based on the graph ID `__ID__`, which is the slugified version of the path.

This is related to #16. #16 has been resolved, but the suggested goal (`[country]-[repository]-[fonds]...-[item]`) creates too long URLs if intermediate levels' IDs include their parent IDs.

If we don't allow a child to have the exact same ID as its parent, then not including an ID part `"some ID"` when the next part starts with that value (e.g. `"some ID / item 1"`).

@mikesname does the front end rely on duplicate parts in URLs? Or can I submit my pull request that fixes this?

### PR DESCRIPTION
**Pull request by bencomp**
Sometimes unit identifiers are absolute on every level. For example: `collection 1` with child `collection 1 / item 1`. Sometimes they are relative to the parent, e.g. `collection 1` with child `item 1`. The URLs for units are based on these IDs, but do not need duplicate parts to make them unique. This change does not prepend `collection 1` to the child's ID for URL generation, because it is already there. Tests are included.

In an effort to understand what is happening during import, I added comments, javadoc or debug log messages to the methods that perform the merge and various other methods.

This also expands the tests for importing Yad Vashem data.

### CODE REVIEW

**Comment by mikesname** [comment]
Nice one, and props on the cleanups. I'll try and review this closely since I have learned from hard experience it's an area fraught with pitfalls.

I actually thought your approach was going to be to modify the identifiers on import, but this might well make more sense, providing there are no gotchas.

What might be a good stress test is to do a import test of lots of existing data and see if we get any unexpected ID collisions.

**Comment by mikesname** [comment]
I'm actually pretty enthused about this approach since it allows us to retroactively redo IDs for items already in the DB and it results in a very nice cleanup.

However, considering this issue has prompted me to realize a pretty major flaw with the current slug system (not even including these changes): because the string replacement (-) is the same as the hierarchy joiner (-), it's pretty easy for two items with different hierarchies and valid identifiers to generate the same ID.

One solution would be to slugify using an underscore and use a hyphen to join hierarchical parts. This would have the secondary advantage that it would convey more information.

However, making this change at the stage would be a major deal since we'd have to regen pretty much all the doc IDs. The pros of doing this are:

 - better now than later
 - there's a redirect DB in place to 301 redirect stuff

I'm leaning in favour of doing this, despite the scariness.

**Comment by bencomp** [comment]
As development went on and rebasing became impossible, I had to merge all the merges. Tests pass though :)

**Comment by mikesname** [comment]
@bencomp hope you don't mind, but I reworked this patch to apply cleanly on master, with the additional slugification changes we've been discussing. If possible I'd like to get it out early this week.

**Pull request closed without merging**
