### PR TITLE
Add licence header and package info to definitions and models packages

### PR DESCRIPTION
**Pull request by bencomp**

### CODE REVIEW

**Comment by mikesname** [comment]
If we're going to do this per-file header can we do every applicable file in one go?

**Comment by bencomp** [comment]
Great idea :)

**Comment by mikesname** [comment]
I think Intellij has a tool for this, will have a look...

**Comment by mikesname** [comment]
Do you think we can get away with not adding it on test sources?

**Comment by bencomp** [comment]
If it's not too much effort, why wouldn't we? Or is it manual labour
after all?

Mike Bryant schreef op 24-03-15 om 11:11:
>
> Do you think we can get away with not adding it on test sources?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EHRI/ehri-rest/pull/124#issuecomment-85434026>.
>

-- 


Ben Companjen
Information systems engineer / Information manager
ben.companjen@dans.knaw.nl
+31 6 1334 9717
Skype: bencompanjen

Data Archiving and Networked Services (DANS)
DANS promotes sustained access to digital research data. See www.dans.knaw.nl for more information and contact details. DANS is an institute of KNAW and NWO.

DANS | Anna van Saksenlaan 51 | 2593 HW The Hague | P.O. Box 93067 | 2509 AB The Hague | +31 70 349 44 50 | info@dans.knaw.nl | www.dans.knaw.nl

**Comment by mikesname** [comment]
Basically it's the visual clutter I object to more than the manual labour.

**Pull request closed without merging**
