### PR TITLE
Clean up of command line utility classes:

### PR DESCRIPTION
**Pull request by mikesname**
- remove copy/paste Javadoc that's not at all helpful
 - add some Javadoc where it hopefully will be more helpful
 - mildly refactor option setting for better encapsulation and
   one-fewer protected fields
 - code reformatting

### CODE REVIEW

**Comment by bencomp** [comment]
Oh man, I spent an hour to fix all these files... Just to see you did the same.

**Comment by mikesname** [comment]
@bencomp oh bummer, can you not merge? I only did it 'cos the internet was down here and I thought it would be an easy thing to do without Google.

**Comment by bencomp** [comment]
That could work; let me try rebasing :)

**Comment by mikesname** [comment]
:boom:

**Pull request merged**
